navigation:
  - text: Shows
    url: "#shows"
  - text: Releases
    url: "#releases"
  - text: Contact
    url: "#contact"
  - text: Merch
    url: "https://thomas-hinds-official-merch.creator-spring.com/"
